class MessageType:
    SERVER_QUIT = 0
    CLIENT_QUIT = 1
    MAP_UPDATE_REQUEST = 2
    SEND_MAP = 3
    CLIENT_HELLO_REQUEST = 4
    MAP_UPDATE_RESPONSE = 5
    SERVER_HELLO_RESPONSE = 6
    MATRIX_STRING_REQUEST = 7
    SEND_MATRIX_STRING = 8
    IDS_UPDATE = 9
    SEND_MAP_NOLOG = 11
